import {
  isEmpty,
  isIdentical,
  isAlpha,
  isAlphaNumeric,
  isValidEmail,
  countWords,
  isAvailable,
  countOccurrences,
  isPasswordStrong,
  isURL,
  isIP,
  isUppercase,
  isLowercase,
  isPalindrome,
  isValidDate,
  isValidPhone,
  isValidCardNumber,
  isAlphanumeric,
  isHash,
  isHexadecimal,
  isASCII,
  isHexColor,
  isJSON,
  isJWT,
  trimRight,
  trimLeft,
  trimBoth,
  getAlphaNumString,
  getLeftSubstring,
  addUnderscore,
  removeSpace,
  removeUnderscore,
} from "./utils/utilityFunctions";


import { isBase32, isBase64, isEthereumAddress ,isStringWithoutSpecialCharacters,startsWithPrefix,endsWithSuffix} from "./utils/validateFunctions";

import { isStringAContainsB, isStringAMatchesB } from "./utils/stringCompareMatch";

const validator = {
  isEmpty,
  isIdentical,
  isAlpha,
  isAlphaNumeric,
  isValidEmail,
  countWords,
  isAvailable,
  countOccurrences,
  isPasswordStrong,
  isURL,
  isIP,
  isUppercase,
  isLowercase,
  isPalindrome,
  isValidDate,
  isValidPhone,
  isValidCardNumber,
  isAlphanumeric,
  isHash,
  isHexadecimal,
  isASCII,
  isHexColor,
  isJSON,
  isJWT,
  isBase32,
  isBase64,
  isEthereumAddress,
  isStringWithoutSpecialCharacters,
  startsWithPrefix,
  endsWithSuffix,
  trimRight,
  trimLeft,
  trimBoth,
  getAlphaNumString,
  getLeftSubstring,
  isStringAContainsB,
  isStringAMatchesB,
  addUnderscore,
  removeSpace,
  removeUnderscore,
};

export default validator;
